[project]
name = "minimal-genjaxmix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipdb>=0.13.13",
    "ipykernel>=6.29.5",
    "jaxtyping>=0.2.36",
    "numpy>=2.2.2",
]
